In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9256, 6082, 8610, 1998],
 [9256, 6082, 8610, 4460],
 [9256, 7878, 8610, 2476],
 [9428, 7873, 6245, 2960, 6080],
 [9428, 7873, 6245, 2960, 3903],
 [2496, 9256, 4791, 8610, 6314],
 [4062, 5616, 3904, 2960]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9256 6082 8610 1998]
 [   0    0    0    0 9256 6082 8610 4460]
 [   0    0    0    0 9256 7878 8610 2476]
 [   0    0    0 9428 7873 6245 2960 6080]
 [   0    0    0 9428 7873 6245 2960 3903]
 [   0    0    0 2496 9256 4791 8610 6314]
 [   0    0    0    0 4062 5616 3904 2960]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\moham\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 238ms/step


array([[[ 0.03406345, -0.01793916, -0.04574154,  0.00259196,
         -0.01743691, -0.00373255,  0.04063893, -0.01083946,
         -0.00618293,  0.01359006],
        [ 0.03406345, -0.01793916, -0.04574154,  0.00259196,
         -0.01743691, -0.00373255,  0.04063893, -0.01083946,
         -0.00618293,  0.01359006],
        [ 0.03406345, -0.01793916, -0.04574154,  0.00259196,
         -0.01743691, -0.00373255,  0.04063893, -0.01083946,
         -0.00618293,  0.01359006],
        [ 0.03406345, -0.01793916, -0.04574154,  0.00259196,
         -0.01743691, -0.00373255,  0.04063893, -0.01083946,
         -0.00618293,  0.01359006],
        [ 0.01116136, -0.02539227, -0.00903768,  0.00983503,
         -0.01872046,  0.0274311 ,  0.02382511, -0.00658754,
          0.04924289, -0.04956968],
        [-0.02509104,  0.01971461,  0.04894557, -0.00706657,
          0.04119947, -0.02803613, -0.00890657, -0.00370162,
         -0.04455322,  0.00362509],
        [ 0.03522595, -0.0348021 ,  0.01273146, -0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 9256, 6082, 8610, 1998], dtype=int32)

In [15]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None